### ISSUE TITLE
loadData() is slow

### ISSUE THREAD

**Issue by zoalst** [metasyn/dreda#8]
I found the load takes over 30 seconds for your sample size of 20000.  
I've got it down to ~18 milliseconds and will submit a pull request soon.  The problem was using underscore to get the size in your loop; it had to execute that code for all 20000 iterations. My fix simply stores the size in a var before starting the loop.  Should I use the group, or submit to your repo? I'm fine with your repo being the main one and ditching the group if you want to.

**Comment by metasyn** [comment]
I ditched the group because I wasn't sure  if you were all to interested. I just re-wrote that function so that it doesn't have x,y,z,cid hardcoded and can take any value.
